# Generated by Django 3.2.12 on 2022-04-05 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=5)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('code', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('service_id', models.PositiveIntegerField()),
                ('trip_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('headsign', models.CharField(max_length=50)),
                ('direction_id', models.PositiveIntegerField()),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_transport.route')),
            ],
        ),
        migrations.CreateModel(
            name='StopTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('stop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_transport.stop')),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_transport.trip')),
            ],
        ),
    ]
