# Generated by Django 3.2.12 on 2022-04-05 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_transport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stoptimes',
            name='arrival_time',
        ),
    ]
