from public_transport.serializers.city import CitySerializer
from public_transport.serializers.route import RouteSerializer
from public_transport.serializers.stop import StopSerializer
from public_transport.serializers.stop_times import StopTimesSerializer
from public_transport.serializers.trip import TripSerializer